#!/usr/bin/env node
// Turn the downloaded OSM extract into src/nairobi-data.js, which the Nairobi map is built from.
//   node tools/osm/build.mjs [--in tools/osm/nairobi-cbd.osm.json] [--out src/nairobi-data.js] [--angle <deg>]
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildMapData, CONFIG } from './pipeline.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const arg = (k, d) => { const i = process.argv.indexOf(k); return i > 0 ? process.argv[i + 1] : d; };
const input = arg('--in', join(here, 'nairobi-cbd.osm.json'));
const out = arg('--out', join(here, '..', '..', 'src', 'nairobi-data.js'));
const angleDeg = arg('--angle');

const osm = JSON.parse(readFileSync(input, 'utf8'));
const data = buildMapData(osm, CONFIG, { angle: angleDeg != null ? (Number(angleDeg) * Math.PI) / 180 : undefined, extra: { fetchedAt: osm.fetchedAt ?? null } });
const js = `// GENERATED by tools/osm/build.mjs from OpenStreetMap. Do not edit by hand; re-run the pipeline.
// Map data © OpenStreetMap contributors, available under the Open Database License (ODbL 1.0).
export default ${JSON.stringify(data)};
`;
writeFileSync(out, js);
const nBox = data.buildings.reduce((s, b) => s + b.boxes.length, 0) + data.roads.reduce((s, r) => s + r.boxes.length, 0);
console.log(`grid angle ${data.meta.angleDeg} deg · ${data.buildings.length} buildings · ${nBox} collider boxes · ${data.streets.length} street labels · ${(js.length / 1024).toFixed(0)} KB -> ${out}`);
